#!/bin/bash
# usage: WekaDecisionStump
#  -a,--arfffile <arg>    ARFF input file (required)
#  -ab,--adaboost         use AdaBoost on the classifier
#  -cv,--crossvalidate    run cross-validation
#  -D,--debug             toggle on debug mode [false]
#  -k,--kfold <arg>       cross-validation k-fold [10]
#  -test,--test           run train/test on datasets
#  -tf,--testfile <arg>   test data file in ARFF format

TRAINFILE=$1
TESTFILE=$2

echo "##########"
echo "########## Weka DecisionStump train/test on $TRAINFILE and $TESTFILE"
echo "##########"

echo "########## >>>>> Weka DecisionStump NO BOOST"
java -server -cp "../weka/build/install/weka/lib/*" org.ncgr.weka.WekaDecisionStump --test --arfffile=$TRAINFILE --testfile=$TESTFILE

echo "########## >>>>> Weka DecisionStump AdaBoost"
java -server -cp "../weka/build/install/weka/lib/*" org.ncgr.weka.WekaDecisionStump --test --arfffile=$TRAINFILE --testfile=$TESTFILE --boostoption=Ada

echo "########## >>>>> Weka DecisionStump LogitBoost"
java -server -cp "../weka/build/install/weka/lib/*" org.ncgr.weka.WekaDecisionStump --test --arfffile=$TRAINFILE --testfile=$TESTFILE --boostoption=Logit

